/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-09-11 12:10:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aboutus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Hotel Online Reservation</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css \" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav style=\"background-color: rgba(0, 0, 0, 0.1);\"\r\n");
      out.write("		class=\"navbar navbar-default\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<div class=\"navbar-header\">\r\n");
      out.write("				<a class=\"navbar-brand\">Hotel Online Reservation</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<ul id=\"menu\">\r\n");
      out.write("		<li><a href=\"HotelMainPage.jsp\">메인 페이지</a></li> |\r\n");
      out.write("		<li><a href=\"aboutus.jsp\">About us</a></li> |\r\n");
      out.write("		<li><a href=\"contactus.jsp\">Contact us</a></li> |\r\n");
      out.write("		<li><a href=\"gallery.jsp\">Gallery</a></li> |\r\n");
      out.write("		<li><a href=\"dineandlounge.jsp\">Dine and Lounge</a></li> |\r\n");
      out.write("		<li><a href=\"reservation.jsp\">Make a reservation</a></li> |\r\n");
      out.write("		<li><a href=\"rulesandregulation.jsp\">Rules and Regulation</a></li>|\r\n");
      out.write("		<li><a href=\"adminLogin.jsp\">Admin Login</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	<div style=\"margin-left: 0;\" class=\"container\">\r\n");
      out.write("		<div class=\"panel panel-default\" style=\"width:1320px;\">\r\n");
      out.write("			<div class=\"panel-body\">\r\n");
      out.write("				<strong><h3>About Us</h3></strong>\r\n");
      out.write("\r\n");
      out.write("				<p style=\"position: relative; float: left; width: 1000px;\">Ginger\r\n");
      out.write("					Hotels is a pioneer, multiple award-winning and most trusted chain\r\n");
      out.write("					of budget hotels in India. One of the leading brands in the\r\n");
      out.write("					hospitality segment, Ginger has rapidly grown in major urban and\r\n");
      out.write("					semi-urban cities across India to be an ideal choice for leisure\r\n");
      out.write("					and business travellers.</p>\r\n");
      out.write("				<img style=\"float: right;\" src=\"images/about.jpg\" width=\"250px\"\r\n");
      out.write("					height=\"150px\" /><br>\r\n");
      out.write("				<p style=\"position: relative; float: left; width: 1000px;\">Explore\r\n");
      out.write("					a new city in India with Ginger Hotels, where you can experience a\r\n");
      out.write("					unique blend of comfort, efficiency, convenience and affordability\r\n");
      out.write("					in warm, smart and interactive social spaces.</p>\r\n");
      out.write("				<br><br><br><br><br><br><br><br>\r\n");
      out.write("				<hr style=\"border: 1px dotted #000;\" />\r\n");
      out.write("				<br />\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"float: left; margin-left: 40px; width: 300px; height: 300px;\">\r\n");
      out.write("					<center>\r\n");
      out.write("						<img src=\"images/1.jpg\" width=\"235px\" height=\"250px\"\r\n");
      out.write("							style=\"margin-top: 5px;\" />\r\n");
      out.write("					</center>\r\n");
      out.write("					<center>\r\n");
      out.write("						<h4 style=\"color: rgba(0, 255, 0, 1);\">Standard</h4>\r\n");
      out.write("					</center>\r\n");
      out.write("					<center>\r\n");
      out.write("						<label>Small Size Bed</label> <label style=\"color: red;\">Php.\r\n");
      out.write("							2,000.00</label>\r\n");
      out.write("					</center>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"float: left; margin-left: 40px; width: 300px; height: 300px;\">\r\n");
      out.write("					<center>\r\n");
      out.write("						<img src=\"images/2.jpg\" width=\"235px\" height=\"250px\"\r\n");
      out.write("							style=\"margin-top: 5px;\" />\r\n");
      out.write("					</center>\r\n");
      out.write("					<center>\r\n");
      out.write("						<h4 style=\"color: rgba(0, 255, 0, 1);\">Extra Bed</h4>\r\n");
      out.write("					</center>\r\n");
      out.write("					<center>\r\n");
      out.write("						<label style=\"color: red;\">Php. 800.00</label>\r\n");
      out.write("					</center>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"float: left; margin-left: 40px; width: 300px; height: 300px;\">\r\n");
      out.write("					<center>\r\n");
      out.write("						<img src=\"images/3.jpg\" width=\"235px\" height=\"250px\"\r\n");
      out.write("							style=\"margin-top: 5px;\" />\r\n");
      out.write("					</center>\r\n");
      out.write("					<center>\r\n");
      out.write("						<h4 style=\"color: rgba(0, 255, 0, 1);\">Superior</h4>\r\n");
      out.write("					</center>\r\n");
      out.write("					<center>\r\n");
      out.write("						<label>1 Medium Size Bed</label> <label style=\"color: red;\">Php.\r\n");
      out.write("							2,400.00 </label>\r\n");
      out.write("					</center>\r\n");
      out.write("				</div>\r\n");
      out.write("				<br style=\"clear: both;\" /> <br />\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"float: left; margin-left: 40px; width: 300px; height: 300px;\">\r\n");
      out.write("					<center>\r\n");
      out.write("						<img src=\"images/4.jpg\" width=\"235px\" height=\"250px\"\r\n");
      out.write("							style=\"margin-top: 5px;\" />\r\n");
      out.write("					</center>\r\n");
      out.write("					<center>\r\n");
      out.write("						<h4 style=\"color: rgba(0, 255, 0, 1);\">Super Deluxe</h4>\r\n");
      out.write("					</center>\r\n");
      out.write("					<center>\r\n");
      out.write("						<label>2 Medium Size Bed</label> <label style=\"color: red;\">Php.\r\n");
      out.write("							2,800.00 </label>\r\n");
      out.write("					</center>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"float: left; margin-left: 40px; width: 300px; height: 300px;\">\r\n");
      out.write("					<center>\r\n");
      out.write("						<img src=\"images/5.jpg\" width=\"235px\" height=\"250px\"\r\n");
      out.write("							style=\"margin-top: 5px;\" />\r\n");
      out.write("					</center>\r\n");
      out.write("					<center>\r\n");
      out.write("						<h4 style=\"color: rgba(0, 255, 0, 1);\">Jr. Suite</h4>\r\n");
      out.write("					</center>\r\n");
      out.write("					<center>\r\n");
      out.write("						<label>Matrimonial</label> <label style=\"color: red;\">Php.\r\n");
      out.write("							3,800.00 </label>\r\n");
      out.write("					</center>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"float: left; margin-left: 40px; width: 300px; height: 300px;\">\r\n");
      out.write("					<center>\r\n");
      out.write("						<img src=\"images/6.jpg\" width=\"235px\" height=\"250px\"\r\n");
      out.write("							style=\"margin-top: 5px;\" />\r\n");
      out.write("					</center>\r\n");
      out.write("					<center>\r\n");
      out.write("						<h4 style=\"color: rgba(0, 255, 0, 1);\">Executive Suite</h4>\r\n");
      out.write("					</center>\r\n");
      out.write("					<center>\r\n");
      out.write("						<label>Matrimonial</label> <label style=\"color: red;\">Php.\r\n");
      out.write("							4,000.00 </label>\r\n");
      out.write("					</center>\r\n");
      out.write("				</div>\r\n");
      out.write("				<br style=\"clear: both;\" /> <br /> <br /> <strong><h3>Amenities\r\n");
      out.write("						and Services</h3></strong>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><label>24 Hour room service</label></li>\r\n");
      out.write("					<li><label>21\" Flat screen TV with cable service</label></li>\r\n");
      out.write("					<li><label>Hot & cold shower</label></li>\r\n");
      out.write("					<li><label>Refrigerator and mini bar on demand in all\r\n");
      out.write("							suites and superior rooms</label></li>\r\n");
      out.write("					<li><label>Coffee & tea set, bottled water, organic\r\n");
      out.write("							tolletries in suites and superior rooms</label></li>\r\n");
      out.write("					<li><label>Hair dryer in suite rooms</label></li>\r\n");
      out.write("					<li><label>Personal safety boxes in every room</label></li>\r\n");
      out.write("					<li><label>Laundry & pressing</label></li>\r\n");
      out.write("					<li><label>Free use Wifi</label></li>\r\n");
      out.write("					<li><label>In room massage services</label></li>\r\n");
      out.write("					<li><label>Personal Safe in Every Room</label></li>\r\n");
      out.write("					<li><label>Mini Bar</label></li>\r\n");
      out.write("					<li><label>7 Function & Meeting Rooms</label></li>\r\n");
      out.write("					<li><label>Road Trip Airport Transfers & Special City\r\n");
      out.write("							Tour</label></li>\r\n");
      out.write("					<li><label>Swimming Pool</label></li>\r\n");
      out.write("					<li><label>Gift Shop</label></li>\r\n");
      out.write("					<li><label>Business Center</label></li>\r\n");
      out.write("					<li><label>Free Parking for Guest</label></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"js/jquery.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
