/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-09-11 08:35:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.connection.DatabaseConnection;

public final class account_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.connection.DatabaseConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Hotel Management System Dashboard</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav style=\"background-color:rgba(0, 0, 0, 0.1);\"\r\n");
      out.write("		class=\"navbar navbar-default\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<div class=\"navbar-header\">\r\n");
      out.write("			<a class=\"navbar-brand\">Hotel Online Reservation</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<div class=\"panel panel-default\">\r\n");
      out.write("			<div class=\"panel-body\">\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("					<ul class=\"nav nav-pills\">\r\n");
      out.write("						<li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("						<li class=\"active\"><a href=\"account.jsp\">Accounts</a></li>\r\n");
      out.write("						<li><a href=\"index.jsp\">Reservation</a></li>\r\n");
      out.write("						<li><a href=\"room.jsp\">Room</a></li>\r\n");
      out.write("						<li><a href=\"logout.jsp\"><span class=\"label label-danger\">");
      out.print((String) session.getAttribute("uname"));
      out.write("</span>&nbsp;Logout</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<br />\r\n");
      out.write("				");

					Connection con = DatabaseConnection.getConnection();
					Statement statement = con.createStatement();
				
      out.write("\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("					<div class=\"panel panel-default\">\r\n");
      out.write("						<div class=\"panel-body\">\r\n");
      out.write("							<div class=\"alert alert-info\">Accounts</div>\r\n");
      out.write("							<a class=\"btn btn-success\" href=\"add_account.jsp\"><i\r\n");
      out.write("								class=\"glyphicon glyphicon-plus\"></i> Create New Account</a> <br />\r\n");
      out.write("							<br />\r\n");
      out.write("							<table id=\"table\" class=\"table table-bordered\">\r\n");
      out.write("								<thead>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th>Id</th>\r\n");
      out.write("										<th>Name</th>\r\n");
      out.write("										<th>Username</th>\r\n");
      out.write("										<th>Password</th>\r\n");
      out.write("										<th>Action</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("								<tbody>\r\n");
      out.write("									");

										ResultSet resultset = statement.executeQuery("select * from admin");
										while (resultset.next()) {
									
      out.write("\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>");
      out.print(resultset.getInt(1));
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(resultset.getString(2));
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(resultset.getString(3));
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(resultset.getString(4));
      out.write("</td>\r\n");
      out.write("										<td><center>\r\n");
      out.write("												<a class=\"btn btn-warning\"\r\n");
      out.write("													href=\"edit_account.jsp?admin_id=");
      out.print(resultset.getInt(1));
      out.write("\"><i\r\n");
      out.write("													class=\"glyphicon glyphicon-edit\"></i> Edit</a> <a\r\n");
      out.write("													class=\"btn btn-danger\"\r\n");
      out.write("													onclick=\"confirmationDelete(this); return false;\"\r\n");
      out.write("													href=\"delete_account.jsp?admin_id=");
      out.print(resultset.getInt(1));
      out.write("\"><i\r\n");
      out.write("													class=\"glyphicon glyphicon-remove\"></i> Delete</a>\r\n");
      out.write("											</center></td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									");

										}
									
      out.write("\r\n");
      out.write("								</tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br />\r\n");
      out.write("	<br />\r\n");
      out.write("	<div style=\"text-align: right; margin-right: 10px;\"\r\n");
      out.write("		class=\"navbar navbar-default navbar-fixed-bottom\">\r\n");
      out.write("		<label>&copy; Copyright HOR 2019 </label>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"../js/jquery.js\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.js\"></script>\r\n");
      out.write("<script src=\"../js/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"../js/dataTables.bootstrap.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function confirmationDelete(anchor) {\r\n");
      out.write("		var conf = confirm(\"Are you sure you want to delete this record?\");\r\n");
      out.write("		if (conf) {\r\n");
      out.write("			window.location = anchor.attr(\"href\");\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		$(\"#table\").DataTable();\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
