/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-09-12 06:31:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.connection.DatabaseConnection;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.connection.DatabaseConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>together homepage</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css \" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav style=\"background-color:rgba(0, 0, 0, 0.1);\"\r\n");
      out.write("		class=\"navbar navbar-default\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<div class=\"navbar-header\" style=\"width: 100%;\">\r\n");
      out.write("			<a class=\"navbar-brand\">투게더</a> <input border=\"1\" width=\"150px;\"\r\n");
      out.write("				type=\"text\" placeholder='Search' \" style=\"border-radius: 15px\">\r\n");
      out.write("			<ul class=\"nav nav-pills\" style=\"float: right;\">\r\n");
      out.write("				<li class=\"active\"><a href=\"home.jsp\">메인</a></li>\r\n");
      out.write("				<li><a href=\"index.jsp\">Reservation</a></li>\r\n");
      out.write("				<li><a href=\"room.jsp\">Room</a></li>\r\n");
      out.write("				<li><a href=\"logout.jsp\"><span class=\"label label-danger\">");
      out.print((String) session.getAttribute("uname"));
      out.write("</span>&nbsp;로그아웃</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<div id=\"myCarousel\" class=\"carousel slide container-fluid\"\r\n");
      out.write("		data-ride=\"carousel\">\r\n");
      out.write("		<ol class=\"carousel-indicators\">\r\n");
      out.write("			<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("			<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("			<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("			<li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>\r\n");
      out.write("			<li data-target=\"#myCarousel\" data-slide-to=\"4\"></li>\r\n");
      out.write("			<li data-target=\"#myCarousel\" data-slide-to=\"5\"></li>\r\n");
      out.write("			<li data-target=\"#myCarousel\" data-slide-to=\"6\"></li>\r\n");
      out.write("		</ol>\r\n");
      out.write("\r\n");
      out.write("		<div style=\"margin: auto;\" class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("			<div class=\"item active\">\r\n");
      out.write("				<img src=\"images/a.jpg\" style=\"width: 100%; height: 450px;\" />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<img src=\"images/b.jpg\" style=\"width: 100%; height: 450px;\" />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<img src=\"images/c.jpg\" style=\"width: 100%; height: 450px;\" />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<img src=\"images/d.jpg\" style=\"width: 100%; height: 450px;\" />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<img src=\"images/e.jpg\" style=\"width: 100%; height: 450px;\" />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<img src=\"images/f.jpeg\" style=\"width: 100%; height: 450px;\" />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<img src=\"images/g.png\" style=\"width: 100%; height: 450px;\" />\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\"\r\n");
      out.write("			data-slide=\"prev\"> <span class=\"glyphicon glyphicon-chevron-left\"\r\n");
      out.write("			aria-hidden=\"true\"></span> <span class=\"sr-only\">Previous</span></a> <a\r\n");
      out.write("			class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\"\r\n");
      out.write("			data-slide=\"next\"> <span\r\n");
      out.write("			class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("			<span class=\"sr-only\">Next</span>\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div style=\"width: 1000px; height: 700px; margin-left: auto; margin-right:auto; position: relative; \">\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"float: left; margin-left: 40px; width: 300px; height: 300px; position: absolute;\" >\r\n");
      out.write("			<center>\r\n");
      out.write("				<img src=\"images/1.jpg\" width=\"235px\" height=\"250px\"\r\n");
      out.write("					style=\"margin-top: 5px;\" />\r\n");
      out.write("			</center>\r\n");
      out.write("			<center>\r\n");
      out.write("				<h4 style=\"color: rgba(0, 255, 0, 1);\">Standard</h4>\r\n");
      out.write("			</center>\r\n");
      out.write("			<center>\r\n");
      out.write("				<label>Small Size Bed</label> <label style=\"color: red;\">Php.\r\n");
      out.write("					2,000.00</label>\r\n");
      out.write("			</center>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"float: left; margin-left: 340px; width: 300px; height: 300px; position: absolute;\">\r\n");
      out.write("			<center>\r\n");
      out.write("				<img src=\"images/2.jpg\" width=\"235px\" height=\"250px\"\r\n");
      out.write("					style=\"margin-top: 5px;\" />\r\n");
      out.write("			</center>\r\n");
      out.write("			<center>\r\n");
      out.write("				<h4 style=\"color: rgba(0, 255, 0, 1);\">Extra Bed</h4>\r\n");
      out.write("			</center>\r\n");
      out.write("			<center>\r\n");
      out.write("				<label style=\"color: red;\">Php. 800.00</label>\r\n");
      out.write("			</center>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"float: left; margin-left: 640px; width: 300px; height: 300px; position: absolute; \">\r\n");
      out.write("			<center>\r\n");
      out.write("				<img src=\"images/3.jpg\" width=\"235px\" height=\"250px\"\r\n");
      out.write("					style=\"margin-top: 5px;\" />\r\n");
      out.write("			</center>\r\n");
      out.write("			<center>\r\n");
      out.write("				<h4 style=\"color: rgba(0, 255, 0, 1);\">Superior</h4>\r\n");
      out.write("			</center>\r\n");
      out.write("			<center>\r\n");
      out.write("				<label>1 Medium Size Bed</label> <label style=\"color: red;\">Php.\r\n");
      out.write("					2,400.00 </label>\r\n");
      out.write("			</center>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br style=\"clear: both;\" /> <br />\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"float: left; margin-left: 40px; margin-top: 300px; width: 300px; height: 300px; position: absolute;\">\r\n");
      out.write("			<center>\r\n");
      out.write("				<img src=\"images/4.jpg\" width=\"235px\" height=\"250px\"\r\n");
      out.write("					style=\"margin-top: 5px;\" />\r\n");
      out.write("			</center>\r\n");
      out.write("			<center>\r\n");
      out.write("				<h4 style=\"color: rgba(0, 255, 0, 1);\">Super Deluxe</h4>\r\n");
      out.write("			</center>\r\n");
      out.write("			<center>\r\n");
      out.write("				<label>2 Medium Size Bed</label> <label style=\"color: red;\">Php.\r\n");
      out.write("					2,800.00 </label>\r\n");
      out.write("			</center>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"float: left; margin-left: 340px; margin-top: 300px; width: 300px; height: 300px; position: absolute;\">\r\n");
      out.write("			<center>\r\n");
      out.write("				<img src=\"images/5.jpg\" width=\"235px\" height=\"250px\"\r\n");
      out.write("					style=\"margin-top: 5px;\" />\r\n");
      out.write("			</center>\r\n");
      out.write("			<center>\r\n");
      out.write("				<h4 style=\"color: rgba(0, 255, 0, 1);\">Jr. Suite</h4>\r\n");
      out.write("			</center>\r\n");
      out.write("			<center>\r\n");
      out.write("				<label>Matrimonial</label> <label style=\"color: red;\">Php.\r\n");
      out.write("					3,800.00 </label>\r\n");
      out.write("			</center>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"float: left; margin-left: 640px; margin-top: 300px; width: 300px; height: 300px; position: absolute;\">\r\n");
      out.write("			<center>\r\n");
      out.write("				<img src=\"images/6.jpg\" width=\"235px\" height=\"250px\"\r\n");
      out.write("					style=\"margin-top: 5px;\" />\r\n");
      out.write("			</center>\r\n");
      out.write("			<center>\r\n");
      out.write("				<h4 style=\"color: rgba(0, 255, 0, 1);\">Executive Suite</h4>\r\n");
      out.write("			</center>\r\n");
      out.write("			<center>\r\n");
      out.write("				<label>Matrimonial</label> <label style=\"color: red;\">Php.\r\n");
      out.write("					4,000.00 </label>\r\n");
      out.write("			</center>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"space\" style=\"width: auto; height: 500px;\"></div>\r\n");
      out.write("	<div style=\"width: 100%; height: 100px; background-color: #ccc\">\r\n");
      out.write("		<div style=\"width: 50%; float: left;\">\r\n");
      out.write("			<p>고객센터</p>\r\n");
      out.write("			<p>주소 : 대전 둔산동 그린 컴퓨터 학원 100호</p>\r\n");
      out.write("			<p>전화 : 042-200-200</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div style=\"width: 50%; float: right; text-align: right;\">\r\n");
      out.write("			<p>회사정보</p>\r\n");
      out.write("			<p>사업자 등록번호 : 152-45147-1487</p>\r\n");
      out.write("			<p>회사 주소 : 대전 둔산동 그린 컴퓨터 학원 1005호</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"../js/jquery.js\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
